export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REFRESH = 'USER_REFRESH';
export const USER_LOGOUT = 'USER_LOGOUT';


export const CLIENT_LOGIN_REQUEST = 'CLIENT_LOGIN_REQUEST';
export const CLIENT_LOGIN_SUCCESS = 'CLIENT_LOGIN_SUCCESS';
export const CLIENT_LOGIN_FAIL = 'CLIENT_LOGIN_FAIL';
export const CLIENT_REGISTER_REQUEST = 'CLIENT_REGISTER_REQUEST';
export const CLIENT_REGISTER_SUCCESS = 'CLIENT_REGISTER_SUCCESS';
export const CLIENT_REFRESH = 'CLIENT_REFRESH';
export const CLIENT_LOGOUT = 'CLIENT_LOGOUT';




export const USER_IN_ADMIN_PANEL = 'USER_IN_ADMIN_PANEL';
export const USER_OUT_ADMIN_PANEL = 'USER_OUT_ADMIN_PANEL';
export const ADMIN_SIDEBAR_POSITION = 'ADMIN_SIDEBAR_POSITION';




