export const REQUEST_ACADEMIC_LEVELS = 'REQUEST_ACADEMIC_LEVELS';
export const REQUEST_ACADEMIC_LEVELS_SUCCESS = 'REQUEST_ACADEMIC_LEVELS_SUCCESS';
export const REQUEST_ACADEMIC_LEVELS_FAIL = 'REQUEST_ACADEMIC_LEVELS_FAIL';
export const REQUEST_CLIENT_ORDERS = 'REQUEST_CLIENT_ORDERS';
export const CLIENT_ORDERS_SUCCESS = 'CLIENT_ORDERS_SUCCESS';
export const CLIENT_ORDERS_FAIL = 'CLIENT_ORDERS_FAIL';
