


export const REQUEST_ACADEMIC_LEVELS = 'REQUEST_ACADEMIC_LEVELS';
export const REQUEST_ACADEMIC_LEVELS_SUCCESS = 'REQUEST_ACADEMIC_LEVELS_SUCCESS';
export const REQUEST_ACADEMIC_LEVELS_FAIL = 'REQUEST_ACADEMIC_LEVELS_FAIL';




export const REQUEST_PREFERED_ENGLISH = 'REQUEST_PREFERED_ENGLISH';
export const REQUEST_PREFERED_ENGLISH_SUCCESS = 'REQUEST_PREFERED_ENGLISH_SUCCESS';
export const REQUEST_PREFERED_ENGLISH_FAIL = 'REQUEST_PREFERED_ENGLISH_FAIL';




export const REQUEST_PAPER_FORMAT = 'REQUEST_PAPER_FORMAT';
export const REQUEST_PAPER_FORMAT_SUCCESS = 'REQUEST_PAPER_FORMAT_SUCCESS';
export const REQUEST_PAPER_FORMAT_FAIL = 'REQUEST_PAPER_FORMAT_FAIL';



export const REQUEST_PAPER_TYPES = 'REQUEST_PAPER_TYPES';
export const REQUEST_PAPER_TYPES_SUCCESS = 'REQUEST_PAPER_TYPES_SUCCESS';
export const REQUEST_PAPER_TYPES_FAIL = 'REQUEST_PAPER_TYPES_FAIL';



export const REQUEST_SUBJECT_AREAS = 'REQUEST_SUBJECT_AREAS';
export const REQUEST_SUBJECT_AREAS_SUCCESS = 'REQUEST_SUBJECT_AREAS_SUCCESS';
export const REQUEST_SUBJECT_AREAS_FAIL = 'REQUEST_SUBJECT_AREAS_FAIL';



export const REQUEST_ORDERS = 'REQUEST_ORDERS';
export const REQUEST_ORDERS_SUCCESS = 'REQUEST_ORDERS_SUCCESS';
export const REQUEST_ORDERS_FAIL = 'REQUEST_ORDERS_FAIL';
